version: '3.5'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: on-failure
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - web-service
    env_file:
      - .env
    tty: true
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - web-service
    env_file:
      - .env
    tty: true
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: on-failure
    volumes:
      - wp:/var/www/html
    expose:
      - "9000"
    networks:
      - web-service
    env_file:
      - .env
    tty: true

volumes:
  db:
    driver_opts:
      type: "none"
      o: bind
      device: /home/jinsecho/data/db
  wp:
    driver_opts:
      type: "none"
      o: bind
      device: /home/jinsecho/data/wp

networks:
  web-service:
    driver: bridge
